name: MaintenancePlugin
main: fr.Boulldogo.MaintenancePlugin.Main
author: Boulldogo 
version: 1.0 
description: Plugin de maintenance pour spigot.
commands: 
  maintenance: 
    permission: maintenance.toggle
    description: Permet d'activer ou de desactiver le mode maintenance.
  maintenance-status:
    permission: maintenance.status
    description: Permet de connaitre le status du mode maintenance.